### ISSUE TITLE
[plugin-optimize-css] Unexpected token when using TypeScript in Script Block

### ISSUE THREAD

**Issue by SarcevicAntonio** [carbon-design-system/carbon-preprocess-svelte#3]
Interested in using the optimizeCss Plugin for production I added it to my vite.config.js. I'm using TypeScript in most Script Blocks and I got this error:
```sh
$ npm run build

> cc-webapp@0.0.0 build
> routify -b && svelte-check && vite build

[Routify] Generated routes in 0 ms

Loading svelte-check in workspace: c:\Users\LinkPlay\dev\first-prototype\FrontEnd
Getting Svelte diagnostics...
====================================

====================================
svelte-check found 0 errors, 0 warnings and 0 hints
vite v2.2.4 building for production...
✓ 26 modules transformed.
[plugin-optimize-css] Unexpected token
file: C:/Users/LinkPlay/dev/first-prototype/FrontEnd/src/pages/matches/[matchId]/watch.svelte
11:   import GameRunner from "./_components/GameRunner.svelte";
12: 
13:   export let matchId: string;
                        ^
14: 
15:   let matchPromise = getMatch(matchId);
error during build:
ParseError: Unexpected token
    at error (C:\Users\LinkPlay\dev\first-prototype\FrontEnd\node_modules\carbon-preprocess-svelte\dist\index.js:19004:18)
    at Parser$1.error (C:\Users\LinkPlay\dev\first-prototype\FrontEnd\node_modules\carbon-preprocess-svelte\dist\index.js:19078:5)
    at Parser$1.acorn_error (C:\Users\LinkPlay\dev\first-prototype\FrontEnd\node_modules\carbon-preprocess-svelte\dist\index.js:19072:10)        
    at Object.read_script [as read] (C:\Users\LinkPlay\dev\first-prototype\FrontEnd\node_modules\carbon-preprocess-svelte\dist\index.js:11539:13)
    at tag (C:\Users\LinkPlay\dev\first-prototype\FrontEnd\node_modules\carbon-preprocess-svelte\dist\index.js:18214:29)
    at new Parser$1 (C:\Users\LinkPlay\dev\first-prototype\FrontEnd\node_modules\carbon-preprocess-svelte\dist\index.js:19038:15)
    at parse$3 (C:\Users\LinkPlay\dev\first-prototype\FrontEnd\node_modules\carbon-preprocess-svelte\dist\index.js:19168:19)
    at extractSelectors (C:\Users\LinkPlay\dev\first-prototype\FrontEnd\node_modules\carbon-preprocess-svelte\dist\index.js:72052:15)
    at Object.transform (C:\Users\LinkPlay\dev\first-prototype\FrontEnd\node_modules\carbon-preprocess-svelte\dist\index.js:72144:27)
    at async ModuleLoader.addModuleSource (C:\Users\LinkPlay\dev\first-prototype\FrontEnd\node_modules\rollup\dist\shared\rollup.js:18451:30)    
```

Hope I didn't raise the alarm too soon. Just letting you guys know. I'm just very glad that you are working on a optimizeCss Plugin 😄 👐

**Comment by metonym** [comment]
@SarcevicAntonio  Thanks for raising this issue. #4 incorporates `svelte-preprocess` to parse TS syntax in Svelte components.

Give it a try in version `0.1.0-rc.4`

---

I've tested it in a minimal SvelteKit + Typescript set-up.

**svelte.config.js**

```js
import preprocess from "svelte-preprocess";
import { optimizeImports, optimizeCss } from "carbon-preprocess-svelte";

const { typescript } = preprocess;

/** @type {import('@sveltejs/kit').Config} */
export default {
  preprocess: [typescript(), optimizeImports()],
  kit: {
    target: "#svelte",
    vite: {
      optimizeDeps: { include: ["clipboard-copy"] },
      plugins: [process.env.NODE_ENV === "production" && optimizeCss()],
    },
  },
};

```

**routes/index.svelte**

```svelte
<script lang="ts">
  import "carbon-components-svelte/css/g10.css";
  import { Link } from "carbon-components-svelte";

  const text: string = "Hello world";
</script>

<Link>{text}</Link>

```

**Result**

Size of the CSS without/with the `optimizeCss` plugin:

```diff
- 463.57kb / brotli: 36.76kb
+ 16.08kb / brotli: 1.31kb
```
