### ISSUE TITLE
[bug, sveltekit] ParseError: Colon is expected

### ISSUE THREAD

**Issue by Grandnainconnu** [carbon-design-system/carbon-preprocess-svelte#8]
On debug and build, I have this error: 
```
ParseError: Colon is expected
    at error (file:///home/grandnainconnu/Documents/projects/work/LesEchoppes/[hidden]/node_modules/carbon-preprocess-svelte/dist/index.mjs:19062:18)
    at Parser$1.error (file:///home/grandnainconnu/Documents/projects/work/LesEchoppes/[hidden]/node_modules/carbon-preprocess-svelte/dist/index.mjs:19136:5)
    at Object.read_style [as read] (file:///home/grandnainconnu/Documents/projects/work/LesEchoppes/[hidden]/node_modules/carbon-preprocess-svelte/dist/index.mjs:15607:15)
    at tag (file:///home/grandnainconnu/Documents/projects/work/LesEchoppes/[hidden]/node_modules/carbon-preprocess-svelte/dist/index.mjs:18272:29)
    at new Parser$1 (file:///home/grandnainconnu/Documents/projects/work/LesEchoppes/l[hidden]/node_modules/carbon-preprocess-svelte/dist/index.mjs:19096:15)
....
```

This error is related to the `Loader` component (see bellow), but I can't understand why.
If you can help,

```
import path from 'path';

import node from '@sveltejs/adapter-node';
import * as carbon from 'carbon-preprocess-svelte';

import preprocess from 'svelte-preprocess';

const { typescript } = preprocess;

export default {
    preprocess: [typescript(), ...carbon.presetCarbon()],
    kit: {
        adapter: node({}),
        ssr: true,
        target: '#svelte',
        vite: {
            optimizeDeps: {
                include: ['clipboard-copy'],
            },
            plugins: [process.env.NODE_ENV === 'production' && carbon.optimizeCss()],
            resolve: {
                alias: {
                    $components: path.resolve('./src/components'),
                    $forms: path.resolve('./src/forms'),
                    $communication: path.resolve('./src/communication'),
                },
            },
        },
    },
};
```

__layout.svelte:
```
<script lang="ts">
	import { prerendering } from '$app/env';

	import Loader from '$components/Loader.svelte';
</script>

{#if prerendering}
	<Loader />
{:else}
	<slot />
{/if}

<style lang="scss" global>
	@import "carbon-components-svelte/css/g10";
</style>
```

Loader.svelte: 
```
<div class="loader">
    <img src='/assets/images/logo.svg' width="80" height="80" alt="Loading" />
</div>

<style lang="scss">
    .loader {
        width: 100%;
        height: 100%;

        margin-top: 20px;
        margin-bottom: 40px;

        display: flex;
        align-items: center;
        justify-content: center;

        img {
            animation: rotateSqueeze 1s linear infinite;
        }

        @keyframes rotateSqueeze {
            from, to {
                transform: translateY(0px) scale(1, 1);
            }
            25% {
                transform: translateY(-20px) scale(1.25, 0.80);
            }
            75% {
                transform: translateY(20px) scale(0.80, 1.25);
            }
        }
    }
</style>
```

**Comment by metonym** [comment]
@Grandnainconnu `presetCarbon` includes the `elements` preprocessor, which only works with valid CSS, not SCSS.

Could you try omitting the `elements` preprocessor since you're using SCSS?

```diff
// svelte.config.js
- import * as carbon from 'carbon-preprocess-svelte';
+ import { optimizeImports } from "carbon-preprocess-svelte";

export default {
- preprocess: [typescript(), ...carbon.presetCarbon()],
+ preprocess: [typescript(), optimizeImports()],
};
```

**Comment by metonym** [comment]
Another solution could be to add the `scss` preprocessor from `svelte-preprocess` before the Carbon-related preprocessors.

**Comment by Grandnainconnu** [comment]
Adding:
```
const { typescript, scss } = preprocess;

export default {
    preprocess: [typescript(), scss(), ...carbon.presetCarbon()],
    ....
}
```

Does the work, but then:
```
Error: Can't find stylesheet to import.
@import "carbon-components/scss/globals/scss/vendor/@carbon/themes/scss";
```

By importing inside the `script` tag it works but I don't know if it's normal behavior

**Comment by metonym** [comment]
Do you have `carbon-components` installed?

**Comment by Grandnainconnu** [comment]
Nop I don't, I took [this](https://github.com/IBM/carbon-components-svelte/tree/master/examples/svite) example to take this `scss` import and in the `package.json` there was no `carbon-components`, but I should install it then?

**Comment by metonym** [comment]
Yes, if you're using SCSS you'll need `carbon-components`.

IRC, in that example it doesn't actually use the SCSS import. It only used `lang="scss"` for the ability to import a stylesheet within a Svelte component without the need for any additional preprocessors.

**Comment by Grandnainconnu** [comment]
Perfect ! Noted, thanks a lot for your reactivity !
